# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

ruby '2.7.6'

gem 'fastlane'
gem 'cocoapods', '>= 1.13', '< 1.15'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
